previews:
  generation: automatic # Enable preview environments

# List all services *except* PostgreSQL databases here
services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    plan: free
    name: conquer-backend
    buildCommand: npm install
    startCommand: npm start